#1.程序名renwu61
.386  	
CODE SEGMENT USE16 
ASSUME CS:CODE
 
START: XOR AX,AX 
       MOV DS,AX 
       MOV AX,3510H 
       INT 21H 
       MOV AH,4CH 
       INT 21H 
CODE ENDS
END START  

#2.程序名renwu62
.386  
STACK   SEGMENT     USE16   STACK
        DB 200  DUP(0)
STACK   ENDS
CODE    SEGMENT     USE16
        ASSUME  CS:CODE,  SS:STACK

START: XOR AX,AX  
       MOV DS,AX 
       XOR BX,BX 
       XOR CX,CX 
       MOV BX,DS:[40H] 
       MOV CX,DS:[42H] 
       MOV AH,4CH 
       INT 21H 
CODE ENDS 
END START
